name: unit-tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        run: redis-server --daemonize yes --port 30000
      - name: Test with pytest
        run: python -m pytest
