name: check-style
on: [push, pull_request]
jobs:
  black-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lgeiger/black-action@master
        with:
          args: ". --check --line-length 120"